### ISSUE TITLE
QIIME otu picker params

### ISSUE THREAD

**Issue by moskalenko** [mikerobeson/Misc_Code#2]
Hi Mike,

Can you share the parameters you used for the qiime otu picker? Also, has the procedure changed since the last time you updated this repo?

Thanks,

Alex

**Comment by mikerobeson** [comment]
Hi @moskalenko, for some reason I just noticed this. Sorry for being several-years to little to late. :-/

I typically try to use high values for `--max_accepts` and `--max_rejects` to avoid OTU-inflation. That is, a read will get mapped to a seed sequence not because it is necessarily the best hit, but because it is an early-hit that fits the match criteria (e.g. within 97% match). On other words, the search terminates before finding a potentially better hit.

At a minimum I use the search termination options for the latest version of usearch as suggested [here](https://www.drive5.com/usearch/manual/termination_options.html). Otherwise I often use something like `--max_accepts 32 --max_rejects 256 `. You can set both to `0` to be exhaustive, but that'll take a long while to run.

*Note, this code is obsolete and I suggest you make use of [this](https://github.com/mikerobeson/make_SILVA_db) procedure.*

**Comment by moskalenko** [comment]
Thanks, Mike.
